# Generated by Django 4.1.3 on 2023-11-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_tag_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["date", "price", "product_name"],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
