# Generated by Django 4.1.3 on 2023-11-10 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_options_product_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-date", "-price", "-product_name"],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
    ]
